
const treatment = {

    "0": {
        "title": "HOW TO DO HOT + COLD SHOWERS",
        "subtitle": "",
        "desc": "Firstly, the cleanliness of your water is of utmost importance when doing hot and cold showers, so ensure you have a filtration system in place to purify your water, if required. Secondly, to get more out of your hot and cold shower routine, try dry skin brushing using a natural-bristle skin brush. Do this right before your hot and cold shower routine for additional benefits. Want to learn more about dry skin brushing?\nNote: while hot and cold showers are generally safe, if you have any sort of medical condition, discuss it with your doctor beforehand. Since both hot and cold put stress on your heart and cardiovascular system, it may be contraindicated for those with serious heart conditions. Listen to your body, and go slowly with your hot and cold tolerance and build up to the full routine, if required.\nHOT AND COLD SHOWER ROUTINE extremes in the beginning. However, you should work on building up to hotter and colder Make sure your bathroom is not too cluttered as temperatures to increase your tolerance and the this also clutters your mind, making you feel less health benefits of the routine. calm. Glass shower panels will help so that you don't feel confined in your shower, again making you feel calmer.\n• Get in the shower and get completely wet at a temperature that is completely comfortable for vou. \n• Slowly increase the temperature to the point you can barely stand it. Expose all areas of the body to this hotter water, including the top of your head and your face. Do this for a minimum of 30 seconds and up to 2 minutes for more effect. \n• Now turn the water down to the coldest tolerable setting, and expose all areas of the body to this colder water. Do this for a minimum of 30 seconds and up to 2 minutes for more effect. \n• Repeat this alternating hot and cold exposure 5 times or more, always ending with cold.\nAt first, your hot and cold tolerance may be minimal, and it is important to honour your extremes in the beginning. However, you should work on building up to hotter and colder temperatures to increase your tolerance and the health benefits of the routine.",
        "links": "vodaretreats.com/product-page/voda-box",
        "image": "https://static.wixstatic.com/media/be6c3a_d0c7553b88cf48e9a017fd87b626c03c~mv2.jpg/v1/fill/w_667,h_539,al_c,q_85/be6c3a_d0c7553b88cf48e9a017fd87b626c03c~mv2.webp",
        "short_desc": "Firstly, the cleanliness of your water is of utmost importance when doing hot and cold showers, so ensure you have a filtration system in place to purify your water, if required. Secondly, to get more out of your hot and cold shower routine, try dry skin brushing using a natural-bristle skin brush.",
    },
    "1": {
        "title": "DRY BRUSHING",
        "subtitle": "SOME TIPS FOR DRY BRUSHING",
        "desc": "Dry brush your skin before a bath or shower. Brushing the skin while it is dry, instead of wet, allows you to exfoliate and increase blood circulation without robbing it of moisture. Then you can wash off any dead skin cells and flaky skin. Be sure to apply a good-quality moisturizer afterward to put moisture back into your skin. \nUse a natural stiff-bristled bath/shower brush. \nWe recommend starting with a fairly soft-bristled brush, as some bristles are stiffer than others, and it depends on your skin's sensitivity and preference. Choose a brush with a long handle to help you reach your back. If your skin is very sensitive, you can use a dry washcloth instead of a natural-bristle brush. Use either a washcloth, a brush designed specifically for the face or an exfoliating face wash on the sensitive skin of your face. \nNever brush over skin that is broken or inflamed. \nThis includes cuts, scrapes, lesions, sores or burned skin, including sunburns. Don't ever brush over areas of infection, redness or general irritation, inflammation, cellulitis or skin cancer.\nSimply skip over these parts until they are fully healed. Stop dry brushing if skin becomes irritated or inflamed.\nHOW TO DRY BRUSH \n• Ensure your skin is completely dry before beginning. The best time is to brush before a shower. \n• Start at the extremities and gently brush toward the heart, applying slight pressure to your personal preference. Move from the feet, up the legs in upward sweeping and circular motions and then from the hands up the arms in the same way. This helps to encourage the lymph tissue toward the nodes for elimination. \n• Use circular motions on the torso (chest, abdomen and back), again encouraging the lymph tissue and circulation towards the heart. \n• Once vou have finished, shower as you normally would, using an exfoliating face wash on your face. \n• Following up with a good-quality moisturizer or serum to help minimize irritation and lock in moisture.",
        "links": "vodaretreats.com/product-page/epic-shower-kit",
        "image": "https://static.wixstatic.com/media/be6c3a_31aa50a4d4714ab289d05e7b07410899~mv2.jpg/v1/fill/w_1040,h_840,al_c,q_85,usm_0.66_1.00_0.01/be6c3a_31aa50a4d4714ab289d05e7b07410899~mv2.webp",
        "short_desc": "Dry brush your skin before a bath or shower. Brushing the skin while it is dry, instead of wet, allows you to exfoliate and increase blood circulation without robbing it of moisture. Then you can wash off any dead skin cells and flaky skin.",
    },
    "2": {
        "title": "INTENTIONS",
        "desc": "Check out the 21 questions below and get to know yourself by reflecting on your answers. After reflecting, create a list of 5 areas you want to make changes in your life and write them out on a post or piece of paper. Now look at these 5 things you have written down and create an intention for each one. \n• What is your proudest accomplishment? \n• What features of my personality do you find most attractive? \n• If you could change one thing about yourself, what would it be and why? \n• If you knew today was the last day of your life what would you do? \n• The last place on earth you would want to visit? \n• What was your first impression of me? \n• When and where do you feel the most protected and cared for? \n• Ultimate date night? \n• Who is your inspiration and why? \n• What is one thing you refuse to share? \n• What is your biggest thing you want to accomplish in the next 5 years? \n• If you could have witnessed any event in \n• History what would it be and why? \n• What is something I do that always makes you laugh? \n• What attracts you most to a potential partner? \n• If you could be instantly talented at one thing what would it be? \n• If you could eat as much of one food as you wanted without ever getting full or fat, which food would you choose? \n• What action or activity makes everyone doing it look stupid? \n• What is something popular now, but everyone will look back at five years from now and think it is stupid and embarrassing? \n• If you could make one thing illegal, what would it be? \n• What is the weirdest thing you have ever seen someone do? \nBONUS: What superhero would improve the world most if he/she existed?",
        "links": "vodaretreats.com/product-page/mindset-is-everything-bundle",
        "image": "https://static.wixstatic.com/media/be6c3a_35aa65482d23448c8f19139ef95d711c~mv2.jpg/v1/fill/w_1160,h_840,al_c,q_85,usm_0.66_1.00_0.01/be6c3a_35aa65482d23448c8f19139ef95d711c~mv2.webp",
        "short_desc": "Check out the 21 questions below and get to know yourself by reflecting on your answers. After reflecting, create a list of 5 areas you want to make changes in your life and write them out on a post or piece of paper. Now look at these 5 things you have written down and create an intention for each one. \n\n• What is your proudest accomplishment?",
    },
    "3": {
        "title": "S'MOREGASBORD",
        "desc": "Want to create the most epic tradition ever? Try a S'MOREgasboard, perfect for everyone's tastes. Mix up your S'more making routine by changing up your ingredients. You can go crazy with the ingredients and try some really great flavor combinations! We love making S'mores by putting roasted marshmallows in between an Oreo cookie for a delectable twist in the classic s'more. \nSo why not get the gang together and put together a S'MOREgasbord potluck night? Have everyone bring their favorite type of Chocolate and cookies - the more different types the better! \nBASES \nThe traditional graham crackers. Add a twist with the cinnamon or chocolate versions \n• Oreos • Crackers • Digestives • Baby Cookies \n• Chocolate Chip Cookies \nChocolate varieties: \n• Hershey Bars • Toblerone • Smarties \n• M&M's • Keto Chocolate \n• Reese Peanut Butter Cups \nAdd your extras: \n• Banana slices • Apple slices • Strawberries \n• Smarties • Candy • Chocolate Chips \n• Pretzels • Bacon • Cinnamon \nGet some dips: \n• Ice cream • Nutella • Peanut Butter • Jams \n• Caramel Sauce • Honey \nSAVORY S'MORES \nHave you tried a savory s'more? Give it a try with these amazing ideas: \nBases: Crackers • Toast • Flat Bread • Pita \nToppings: Mozzarella balls • Goat cheese \n• Prosciutto • Bacon • Basil • Pear • Apples • \nWalnuts • Chocolate \nDips and drizzles: Hot Chili Oil • Aioli • Mayo \n• Cheese Dip • Spinach Dip • Balsamic Vinegar reduction \nThe possibilities are endless! We would love to see what you came up with so tag us on Instagram with #Vodamoments.",
        "links": "vodaretreats.com/product-page/s-more-spice-matcha-melt",
        "image": "https://static.wixstatic.com/media/be6c3a_59878b0ae39348f1956be897872bd89e~mv2.png/v1/fill/w_1040,h_840,al_c,q_90,usm_0.66_1.00_0.01/be6c3a_59878b0ae39348f1956be897872bd89e~mv2.webp",
        "short_desc": "Want to create the most epic tradition ever? Try a S'MOREgasboard, perfect for everyone's tastes. Mix up your S'more making routine by changing up your ingredients. You can go crazy with the ingredients and try some really great flavor combinations!",
    },
    "4": {
        "title": "ULTIMATE HOT CHOCOLATE",
        "desc": "I am obsessed with Chocolate! I crave its sweet and silky texture. I also adore enjoying some comforting hygge with a hot beverage, whether it be a cup of tea, broth or the ultimate hot chocolate. Enjoy some hygge with this Ultimate Hot Chocolate recipe! \nINGREDIENTS \n4 cups milk or your favorite milk alternative \n1 cinnamon stick \n2 split vanilla bean (optional) or teaspoon pure vanilla extract \n10 ounces semisweet or milk chocolate, cut into small piece or your Teaspressa Hot Chocolate Kit \nWhipped cream, for serving (optional) \nChocolate shavings (optional) \nINSTRUCTIONS \nHeat milk to scalding in a medium saucepan. Add cinnamon, and vanilla, if desired. Let steep for 10 minutes. Remove saucepan from heat; strain, and return to saucepan. \nIf making from scratch Reheat milk; using a whisk, stir in chocolate until melted and milk is frothy. \nIf using Teaspressa muddle the chocolate and sugar cubes in a mug and pour warmed milk over top. Add the marshmallow cubes. \nServe immediately with a dollop of whipped cream garnished with chocolate shavings, if desired. ",
        "short_desc": "I am obsessed with Chocolate! I crave its sweet and silky texture. I also adore enjoying some comforting hygge with a hot beverage, whether it be a cup of tea, broth or the ultimate hot chocolate. Enjoy some hygge with this Ultimate Hot Chocolate recipe!",
        "links": "vodaretreats.com/product-page/chocolate-excellence-bath-fizz-50g",
        "image": "https://static.wixstatic.com/media/be6c3a_00ebefd1b89440839b7388d0442caa98~mv2.jpg/v1/fill/w_1040,h_840,al_c,q_85,usm_0.66_1.00_0.01/be6c3a_00ebefd1b89440839b7388d0442caa98~mv2.webp",
    },
    "5": {
        "title": "HOW DO I CREATE TRADITIONS?",
        "desc": "Most of us have traditions we have created over the years with family and friends, particularly around the holiday season. Our traditions help us create connections and make us feel like we belong. They give us a sense of inner peace and self-acceptance of our strengths and weaknesses and feeling grounded in our core identity. Traditions bring comfort from being part of a group of people such as a family or team that share our values and provide support, respect and friendship. \nUnlike our daily routines, our traditions are conscious activities we do with a specific purpose or desire in mind. By creating and maintaining traditions in our life, big or small, we can create a sense of calm to look forward to in our day, such as enjoying a cup of tea in the morning or an afternoon sweet treat with friends \nTake charge.\nWhile some traditions occur naturally, such as getting a Christmas tree or a Hanukkah bush, others may require some finagling. Do not be afraid to invite your family to join you for an activity you already do. For example, my dad had a tradition of visiting a chocolate shop about an hour away from our house every year at Christmastime to buy gifts. \nAfter a few years of doing this alone, he invited me and my mom to join him on his journey (it took about a month to find a day we could all go that first year). Now we go every year, and we make a day of it. We drive up, buy our gifts, window-shop around the town, and get lunch together. My dad first took the initiative to invite us, but this shopping trip is now a great tradition that I have with my parents.",
        "links": "vodaretreats.com/product-page/portable-bonfire-kit",
        "image": "https://static.wixstatic.com/media/be6c3a_cdaf058da5c84dbfa1b65ef8a40acf87~mv2.jpg/v1/fill/w_1040,h_840,al_c,q_85,usm_0.66_1.00_0.01/be6c3a_cdaf058da5c84dbfa1b65ef8a40acf87~mv2.webp",
        "short_desc": "Most of us have traditions we have created over the years with family and friends, particularly around the holiday season. Our traditions help us create connections and make us feel like we belong. They give us a sense of inner peace and self-acceptance of our strengths and weaknesses and feeling grounded in our core identity.",
    },
    "6": {
        "title": "DIGITAL DETOX",
        "desc": "Better productivity and wellbeing are waiting for you offline! Our biggest and best ideas come to us when we let our minds wander... yet our days are spent attempting to focus on 1000 different things. As our lives become increasingly busy and distracted and we spend more and more time online, our bodies naturally start to crave rest, relaxation and a slower pace of life. The Solution? A slow-living approach and a digital detox. \nThe concept is simple. Literally. Instead of celebrating being busy, slow-living celebrates a life where actions are taken for their impact, not to fill up space on a calendar. Slow-living is all about simplifying your life, removing the non- essentials and leaving empty space in their place. Bring some of the art of slow-living into your own life by reevaluating how you spend your time. What's working for you? What's just another distraction? This should include a digital cleanse or digital detox. Go through your digital devices, your apps, your social media platforms and remove anything that isn't serving you. Then, attempt a digital detox! \nTHE BENEFITS OF A DIGITAL DETOX \nCalm down and feel content. Several social experiments found that taking a scheduled break away from smartphones or digital devices can lower stress levels. It can also help you focus on the present and pay more attention to things around you. \nBe more productive. Scrolling, liking, posting, or just surfing the internet can be time consuming. It can leach time away from not only your responsibilities, but also other activities that bring you joy and 'fill your cup'. Setting your phone aside will help you focus on things you need to get done. \nFeel better about yourself. Social media apps lead you to compare yourself with others constantly. That can affect how you see yourself. Cutting back on phone time can boost your self-image and self-esteem.",
        "links": "vodaretreats.com/product-page/pineapple-bliss-revitalizing-raw-juice-mask",
        "image": "https://static.wixstatic.com/media/be6c3a_c0e5057f867c4e978795b655279000de~mv2.jpeg/v1/fill/w_1040,h_840,al_c,q_85,usm_0.66_1.00_0.01/be6c3a_c0e5057f867c4e978795b655279000de~mv2.webp",
        "short_desc": "Better productivity and wellbeing are waiting for you offline! Our biggest and best ideas come to us when we let our minds wander... yet our days are spent attempting to focus on 1000 different things. As our lives become increasingly busy and distracted and we spend more and more time online, our bodies naturally start to crave rest, relaxation and a slower pace of life.",
    },
    "7": {
        "title": "TRATAK: GAZING MEDITATION",
        "desc": "Tratak is a sanskrit word meaning fixed gazing and involves staring at an object to calm the mind. You may find yourself doing this when you 'zone out' from time to time, but taking the time to actively focus and bring awareness to the gaze can be a meditative practice. As we know, meditation can reduce tension, stress and anxiety which can lead to all sorts of physical and mental benefits. The beauty of this form of meditation is that it is wonderfully inconspicuous and so you can practice it anywhere! You can gaze meditatively at something during a meeting, on a bus, or in a waiting room. \nThe guidelines are simple: find an object within vour line of vision that you might want to fix your eyes on and take several belly breaths as vou steady your eyes on the object. Let it capture your interest, as though it were the only object in the vicinity. Try not to judge what you are seeing, or have any thoughts about it all; see if you can have the experience of 'just seeing.' When thoughts arise, note them and then return your focus to the object. \nOne way to practice this type of meditation is by staring at the flame of a candle, like the candles from our partner Contrail Candles. You can grab one of our exclusive collaboration with them on our website on its own or in our Love + Connection Experience. Follow the instructions on the other side to give it a try!",
        "short_desc": "Tratak is a sanskrit word meaning fixed gazing and involves staring at an object to calm the mind. You may find yourself doing this when you 'zone out' from time to time, but taking the time to actively focus and bring awareness to the gaze can be a meditative practice. As we know, meditation can reduce tension, stress and anxiety which can lead to all sorts of physical and mental benefits.",
        "links": "vodaretreats.com/product-page/hand-poured-soy-candles-4oz",
        "image": "https://static.wixstatic.com/media/be6c3a_e1598417fc5048fe8908d793f92ab99c~mv2.jpg/v1/fill/w_1040,h_840,al_c,q_85,usm_0.66_1.00_0.01/be6c3a_e1598417fc5048fe8908d793f92ab99c~mv2.webp",
    },
};

export default treatment;
//https://static.wixstatic.com/media/be6c3a_cdaf058da5c84dbfa1b65ef8a40acf87~mv2.jpg/v1/fill/w_1040,h_840,al_c,q_85,usm_0.66_1.00_0.01/be6c3a_cdaf058da5c84dbfa1b65ef8a40acf87~mv2.webp
